Prep-javascript-variables exercise - Jenn Noh
jennifernoh/prep-0722-code-solutions pull request #10
Opened 2022-08-10 05:34 UTC by jennifernoh

<img width="952" alt="Screen Shot 2022-08-09 at 10 31 24 PM" src="https://user-images.githubusercontent.com/110091297/183823293-8b965125-dcbe-4c52-ba0d-6788709af15f.png">

2022-08-10 18:10 UTC, thebearingedge requested changes

2022-08-10 18:10 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +    var nothing = '';
Hi Jennifer, for this variable we want to assign it the value `null` instead of an empty string.

2022-08-12 05:54 UTC, jennifernoh commented
<img width="937" alt="Screen Shot 2022-08-11 at 10 53 14 PM" src="https://user-images.githubusercontent.com/110091297/184293098-dc282905-32eb-4aca-a8d4-90a67c706e9a.png">

2022-08-12 14:49 UTC, thebearingedge approved these changes

2022-08-13 05:36 UTC, merged